### ISSUE TITLE
DCSOps hours have not transferred to Volunteer Connection since February 12, 2017

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#101]
This issue is affecting all DCSOPs-using Regions.

**Comment by kfogel** [comment]
@cecilia-donnelly @bnazari, this issue can be closed now, right?  Is any further verification needed?

**Comment by OhMcGoo** [comment]
I don't believe this issue has been resolved completely. Let me do a little testing.

**Comment by OhMcGoo** [comment]
This is @kfogel being ventriloquized by @OhMcGoo (sharing a keyboard):

This issue is resolved, so I'm closing it.  There is still a question about whether hours are being exported correctly in bundles of 40 (the workaround for VC's hours-ingestion limit), but that is being tracked in issue #34.  @OhMcGoo has an idea for how to test that and will comment about it in issue #34 when ready.
