### ISSUE TITLE
Document and adhere to a dev->deployment policy.

### ISSUE THREAD

**Issue by kfogel** [redcross/arcdata#108]
As noted in [this comment](https://github.com/redcross/arcdata/pull/106#issuecomment-343711639), we need a documented development+deployment policy.  For now, I propose simply:

Master should always be deployable, and tip of master is normally what is deployed.  If a rollback must be done, the prod site gets rolled back to some previous commit on master.  Development is done on branches, and those branches are merged when they pass the tests and are deemed safe for deployment.

**Comment by tfe** [comment]
Generally agreed, in fact I'd advocate automatically deploying master whenever new commits are merged (via TravisCI or some other mechanism).

Rollbacks can be done either by committing a revert of a previous bad merge. If a quicker rollback is needed, a `heroku rollback` can be done first followed up by a proper revert on master (which then gets deployed as normal).

**Comment by kfogel** [comment]
Okay, this is done in commit f9379e0.  Closing.

Thanks for the comments, btw, @tfe.  I think we might want to move to automated deployments at some point in the near future.  But for now, I'd like to keep doing them manually, so that we know a human is present and paying attention when a deployment is done -- that way if anything goes wrong, we will know right away and can roll back.
