### ISSUE TITLE
Verify and document deployment procedure.

### ISSUE THREAD

**Issue by kfogel** [redcross/arcdata#118]
We should verify the deploy-to-Heroku procedure itself before including any actual code changes in a deployment, as discussed in the 2017-11-21 meeting.  Let's have two people "on duty" for this first deployment, just as insurance.  It's highly unlikely anything will go wrong, but if something does, there would be two minds available to solve it instead of just one.  I've assigned this issue to @pjsier so far, and will add @pmacaluso3 as soon as he accepts the GitHub team invitation I just sent :-).

The overall deployment procedure is documented (in the "Deployment" section in [`INSTALL.md`](https://github.com/redcross/arcdata/blob/master/INSTALL.md)), and that documentation should be verified.  Once a particular deployment is completed, it should be logged in [`docs/site-updates.txt`](https://github.com/redcross/arcdata/blob/master/doc/site-updates.txt).

Commit b103f31e is a fine one to use for this test deployment.  There were no code changes going back from that one to commit 24a773e3, which is what is currently deployed on the server.

**Comment by pjsier** [comment]
Making a note for this that we should include in `INSTALL.md` that if the database credentials are changed, we'll also need to make sure Periscope is updated with those credentials

**Comment by cecilia-donnelly** [comment]
@pjsier, I think if you add the note about Periscope to INSTALL.md then we can close this issue.

**Comment by pjsier** [comment]
@cecilia-donnelly Updated in 1b3b4e2

**Comment by cecilia-donnelly** [comment]
Thanks @pjsier!
