### ISSUE TITLE
Verify that backups are happening, and document how.

### ISSUE THREAD

**Issue by kfogel** [redcross/arcdata#121]
The DCSOps database is being backed up, right?  Riiiiiiight?  I mean, I'm sure it is, but we need to find out exactly how & where, and verify (in a dev sandbox) that a restore is possible.

I'm not sure where to look for this in Heroku, but that's where I'd start.  Please ping me if you have questions or if you look and don't find any backup mechanism in place -- if we can't find any backups, then this issue will suddenly get _very urgent_.

**Comment by tfe** [comment]
Just wanted to chime in quickly to put your mind at ease, there are automated daily backups currently. You can see them by running `heroku pg:backups --app arcdata`.

**Comment by kfogel** [comment]
Hey, thank you @tfe!  That is very reassuring.

**Comment by kfogel** [comment]
@pmacaluso3 and @pjsier, can you use one of those backups to test out a local deployment?  If you can deploy with that data locally, then that confirms that we can do a restore if ever needed.

**Comment by pjsier** [comment]
@kfogel just got this set up locally without any issues. I created a user in one of the existing chapters, logged in with the legacy login URL, and everything seems to be fine. The backups work with `pg_dump` and `pg_restore`, so they're pretty easy to use as well. Here's some more detailed info if we want to add anything to the docs https://devcenter.heroku.com/articles/heroku-postgres-import-export

**Comment by kfogel** [comment]
@pjsier w00t!  Thanks.

Do you feel ready to do the trivial redeployment of the production service on Heroku?  I'd like to know that @pmacaluso3 has also gotten it stood up locally too before we move on to that, but knowing that you're ready would be a big step forward in itself.

-Karl "Caution Acquired Through Experience Not Temperament" Fogel :-)

**Comment by pjsier** [comment]
Definitely! Once he’s got his local setup going I think the initial
deployment will be easy

**Comment by cecilia-donnelly** [comment]
@pjsier, can you document the backups in INSTALL.md or a new DESIGN.md?  Then I think we can close this.

**Comment by pjsier** [comment]
@cecilia-donnelly updated along with the mention of Periscope in 1b3b4e2. Let me know if that covers all of the information

**Comment by cecilia-donnelly** [comment]
@pjsier thanks!  Earlier in this thread @tfe mentioned that there are automated daily backups in our prod instance.  Can you add a note about that?  It could be of the form "We run automated daily backups in Heroku.  To do so in your copy of the app, [link to documentation or prose description of how we handle this]."  How would a person verify that the backups exist and are working correctly?

**Comment by pjsier** [comment]
@cecilia-donnelly good point, just updated that with some example commands

**Comment by cecilia-donnelly** [comment]
Thanks @pjsier!  We can update that as needed, if our backups system changes.  Closing this now.
