### ISSUE TITLE
Update Heroku database PostgreSQL versions

### ISSUE THREAD

**Issue by pjsier** [redcross/arcdata#122]
Currently, the Heroku databases are on Postgres versions 9.3, 9.4, and 9.5, with one test instance on 9.6. All of these should be updated to 9.6

**Comment by pmacaluso3** [comment]
I believe this will get fixed incidentally as part of https://github.com/redcross/arcdata/issues/142. If it does not, I will revisit this issue.

**Comment by kfogel** [comment]
**nod** Thanks, @pmacaluso3.  That sounds reasonable.

**Comment by pmacaluso3** [comment]
Fixed as part of #142
