### ISSUE TITLE
Allow up to 20 flex responders on responder console

### ISSUE THREAD

**Issue by tmoerbitz** [redcross/arcdata#128]
While dispatching, we are limited to a small number of members that appear on the flex schedule in the responder console.  Is it possible to modify the console to display a minimum of 20 flex responders on one page.  In the Minnesota Region, we typically only see about 7-8 flex responders, even though we know we regularly have 30-40 flex responders available.  

<img width="1157" alt="screen shot 2017-12-26 at 6 09 43 pm" src="https://user-images.githubusercontent.com/34872148/34366955-ef09622c-ea68-11e7-807f-d7845908544e.png">

**Comment by kfogel** [comment]
https://www.dcsops.org/incidents/REGION_SLUG/incidents/INCIDENT_NUMBER/responders

Example REGION_SLUG: "cni"

Example INCIDENT_NUMBER: "20-0739"

**Comment by kfogel** [comment]
Display up to 20 flex responders, but don't bother to implement pagination yet -- it wouldn't actually help, because if you don't have responders available that's a scheduling issue not an application UI issue.

**Comment by frankduncan** [comment]
There is no limit to the number of responders displayed in the responder console.  Will need to get a more current example to analyze, but there is a culling of which responders can show up in the console depending on the Shift Territories (or Counties in the old system) for which they are enabled.

@OhMcGoo We can go over this on Monday.

**Comment by frankduncan** [comment]
The conclusion is that this issue is indeed invalid.

**Comment by frankduncan** [comment]
Ah ha!  I was wrong and there IS a limit.  Which I've now found.  How the limit interacts with the actual query is non straightforward because it does the limit BEFORE doing the uniqueness, so a limit of 15 might only show 5-10 responders.  I'm going to increase the limit to 100 to show everything for right now.  I'll let MN decide if that's too much.

**Comment by frankduncan** [comment]
I can't reorder the uniqueness/limit because of how I'm looking at what uniq does in the rails 5 upgrade.
