### ISSUE TITLE
Scope and Chapter admin pages return errors

### ISSUE THREAD

**Issue by pjsier** [redcross/arcdata#136]
The scope and chapter admin pages are both returning 500 errors, likely because of changes to ActiveAdmin introduced in the last Gemfile upgrade.

The custom serializers from `arcdata_core` override `has_attribute?` on these models, and require the argument provided to that method to respond to `to_sym`. ActiveAdmin calls `has_attribute?` to check column types in the version we're using, but since it's calling it with a Proc (for actions) it fails on these admin pages.

The easiest way to fix this since the serializers have custom logic is to monkey patch the method in ActiveAdmin that calls `has_attribute?` and check that the argument it's receiving isn't a descendant of `Core::SerializedColumns` which has this behavior. About to submit a PR implementing this

**Comment by pjsier** [comment]
Confirmed as resolved by #137

**Comment by kfogel** [comment]
W00t!  Thanks @pjsier.  Fastest open-and-close of an issue ever :-).
