### ISSUE TITLE
Permit resending of recruitment messages from the Responder Console and individual messaging to unassigned responders

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#140]
Currently, dispatchers can send a one-time recruitment message to potential responders via the Responder Console. Add additional functionality that will permit:

- "Resetting" the Responder Console so that subsequent recruitment messages can be sent
- Allowing individual messages to be sent to potential responders regardless of status (Available, Declined, Message Sent). For example, a potential responder may reply "Yes" to a recruitment message but may not be needed because a team has already been identified. The dispatcher should be able to message the responder to let them know that they are not needed or ask them be on standby.

<img width="1162" alt="responder console" src="https://user-images.githubusercontent.com/4147733/35007221-93342a98-fabe-11e7-8123-55b44b2f2ee0.png">

**Comment by bnazari** [comment]
Brilliant idea. Just to define the process a bit more, I have a couple of questions:

Do we want the ability to send a blanket response to everyone, possibly with filters? (e.g. Send “Client decided to stay with cousin, no response needed.” to everyone that responded Available)
Do we want the canned responses the DO can choose from a list or just free text?
Do we want the ability to get responses form these text messages or are they just outbound?

**Comment by OhMcGoo** [comment]
@bnazari: **See my replies inline.**

Do we want the ability to send a blanket response to everyone, possibly with filters? (e.g. Send “Client decided to stay with cousin, no response needed.” to everyone that responded Available)

**Resetting the Responder Console would allow for resending a blanket message.**

Do we want the canned responses the DO can choose from a list or just free text?

**Yes! I think a pop-up menu with simple, straightforward responses would be nice.**

Do we want the ability to get responses form these text messages or are they just outbound?

**Yes, seeing individual responses is important.**

**Comment by kfogel** [comment]
Jim's UI suggestion:

In the "Available Responders" table at the bottom of the page, make these changes:

1. In the "Assign" column, make it be an "Actions" drop-down as is already available in the "Responders" (i.e. people already assigned & accepted) table at the top, instead of just an "Assign" link.  In this new "Actions" drop-down, make "Assign" be one of the actions.

2. The "Recruit" column link should change from "Send SMS" to "Send recruitment message" or something like that (because blasting that common initial message easily is still important to be able to do).

**Comment by frankduncan** [comment]
After more discussion, the to follow up on @kfogel #1 above, there will be two new items: "Send recruitment message" and "Send individual message" that allows dispatchers to do what the action says.

There's no longer a need to reset the entire interface.

**Comment by frankduncan** [comment]
After a first pass, it looks like if I send a recruitment message again after they responded, the recruit status changes from Avaliable/Unavailable back to Message Sent.  

Is that ok @OhMcGoo ?  Or should there be different messaging?

**Comment by OhMcGoo** [comment]
@frankduncan: Just the recruitment message or the new individual message as well?

**Comment by frankduncan** [comment]
Just the recruitment message

**Comment by frankduncan** [comment]
@OhMcGoo ^^

**Comment by OhMcGoo** [comment]
@frankduncan: That should be fine.
