### ISSUE TITLE
"Show Roster" hyperlink is malfunctioning

### ISSUE THREAD

**Issue by pgrau2342** [redcross/arcdata#148]
On the DAT Scheduling screen, there is a "Show Roster" link. When you click on the link, you receive an "Application Error".

![image](https://user-images.githubusercontent.com/34947498/35747214-18bd720c-080f-11e8-943f-a1652de3d18d.png)

Issue is not critical at this time, but would be very helpful to get fixed. Thanks.

Pete Rau

**Comment by OhMcGoo** [comment]
On the **DAT Scheduling** page, repair the Show Roster link. When clicking the link, the page typically times out creating an error message.

<img width="845" alt="show roster" src="https://user-images.githubusercontent.com/4147733/65566240-de665100-df17-11e9-9e80-cc8f9f1bdae2.png">

**Comment by kfogel** [comment]
The URL is https://www.dcsops.org/scheduler/people, and it's been broken for a long time.  But @OhMcGoo says there is definitely a roster -- we just have to figure out how to get it to load.
