### ISSUE TITLE
Reduce logging to Sentry with Raven

### ISSUE THREAD

**Issue by pjsier** [redcross/arcdata#154]
We went over the monthly limit on the Sentry free tier (10,000 errors logged monthly), but most of these are `CasCredentialErrors` or the `SMTP` issue we ran into before. We should suppress these so that we can stay within the free tier

**Comment by kfogel** [comment]
That sounds like an easy change, and there's a deployment planned for this week.  Do you have time to make this change today so that it goes into production with that deployment?

**Comment by pjsier** [comment]
@kfogel just merged this since it's a pretty safe configuration change, so it'll be part of the deployment tomorrow
