### ISSUE TITLE
Some chapter's Twilio SMS notifications are failing

### ISSUE THREAD

**Issue by pjsier** [redcross/arcdata#155]
Multiple chapters are getting this error messages when trying to send SMS:

`Twilio::REST::RequestError: The From phone number {PHONE_NUMBER} is not a valid, SMS-capable inbound phone number or short code for your account.`

Twilio credentials are configured on a per-chapter basis, and not as general environment variables, but this looks like it might have to do with the general Twilio account configuration. The following chapters have had this error in the past few days (but there may be more):

* Nebraska
* Southern Minnesota
* Gold Country

**Comment by pjsier** [comment]
This was because Twilio was transferred to another account, but not all of the chapter credentials were updated. All of the chapters are now using the current credentials, and I'm guessing this probably closes #153 as well. Leaving open until we can confirm though

**Comment by OhMcGoo** [comment]
@pjsier: To update a Chapter's credentials in DCSOps, do I need to update the SID **_and_** the Twilio authentication token? If so, where do I find the token string?
<img width="1280" alt="twilio" src="https://user-images.githubusercontent.com/4147733/36388296-046cdb76-1561-11e8-9d3c-67fe16092ac8.png">

**Comment by pjsier** [comment]
@OhMcGoo it's actually already updated, so we should be good to go! We may need to change them though since the screenshot contained the Twilio credentials though

**Comment by OhMcGoo** [comment]
My bad. Can I simply delete my post?

**Comment by pjsier** [comment]
@OhMcGoo no problem, it happens! I deleted it online already, so it wasn't up for more than a minute or so. @kfogel should we still update the Twilio credentials to be safe?

**Comment by kfogel** [comment]
@pjsier These are shared creds across all the chapters?  And they were visible in this issue briefly?

My initial thought is that we don't need to update them, if they were only visible for a few minutes or so, but that partly depends on what these credentials enable and how much of a pain it is to cycle them.  If they would give someone the ability to send a gazillion text messages, and have the Red Cross get billed for it, then I'm afraid we should update them...

**Comment by pjsier** [comment]
@kfogel it's not too difficult to change them so I'll do that now and then update the site updates log

**Comment by OhMcGoo** [comment]
This issue has been resolved.
