### ISSUE TITLE
Set up LetsEncrypt auto-renew for TLS certs (https://).

### ISSUE THREAD

**Issue by kfogel** [redcross/arcdata#159]
We're now using a LetsEncrypt cert (which is good), but it may not be set up yet to auto-renew before its 90 days are up.  We should make sure it auto-renews every 60 days or so, so that if something goes wrong we get an error and still have 30 days to solve it.

See [this thread](https://groups.google.com/forum/#!topic/dcsops-dev/6IZRgjeEABg), and in particular [this message](https://groups.google.com/d/msg/dcsops-dev/6IZRgjeEABg/Z8OcnBmfBQAJ), for details.

**Comment by pjsier** [comment]
I think it might actually be better to go with Heroku's [Automated Certificate Management](https://devcenter.heroku.com/articles/automated-certificate-management). It comes free with any paid account, and it looks like a lot of projects that try to support Let's Encrypt on Heroku are suggesting people move that direction (one example: https://github.com/substrakt/letsencrypt-heroku)

**Comment by OhMcGoo** [comment]
Is this still necessary?

**Comment by pjsier** [comment]
@OhMcGoo no, but I just made an issue for moving over to Heroku's free SSL. I can migrate the DNS tonight (since it'll be pointing to the same thing there shouldn't be any service interruptions) and then remove the extra add-on once it's done
