### ISSUE TITLE
Update "DCSOps" name to "DATResponse" throughout the code base.

### ISSUE THREAD

**Issue by kfogel** [redcross/arcdata#162]
Summary says all.

(By the way, didn't we also have an issue for changing this *repository's* name from "arcdata" to "dcsops"-now-"datresponse" as well?  I can't find it right now, but if that issue exists it should be linked to from this issue.)

**Comment by OhMcGoo** [comment]
Having assumed ownership of the domain dcsops.org, these changes are no longer needed.
