### ISSUE TITLE
Tell Direct Line about the new From address on incoming webhook-bound emails.

### ISSUE THREAD

**Issue by kfogel** [redcross/arcdata#163]
As per our discussion with @pjsier, someone at Direct Line should be told that emails coming from DCSOps -- and going to (presumably) a webhook at Postmark that then feeds scheduling info into Direct Line -- are going to look like they're coming from

    DAT Scheduling <directline.export {_AT_} datresponse.org>

soon (instead of from `dcsops.org`).  Yes, I've spam-obscured the email address a little bit above, in the obvious way -- see the top of `app/mailers/scheduler/directline_mailer.rb` for full context.

We need the person at Direct Line to confirm that they'll be able to process that incoming webhook info just fine.  They may or may not need to make any changes on their end to handle the new From address.

**Comment by OhMcGoo** [comment]
Correspondence sent to John Freire of Direct Line:

"John:

For less than ideal reasons, DCSOps will be moving to a new domain on July 1: www.datresponse.org. As such, the schedule e-mails you receive will be sent from a different e-mail address: directline.export@datresponse.org. Again, this change won’t be happening until the end of the month but I wanted to let you know it’s coming. I’ll reach out when we get closer to the cutover so we can test the new setup.

Thanks,

Jim McGowan"

**Comment by OhMcGoo** [comment]
With control of the dcsops.org domain, the following was sent to John Freire of Direct Line:

John:

We were actually able to get control of the domain dcsops.org so the changes we were expecting to implement are no longer needed. We will continue to send Direct Line regional rosters as normal.

How did your conversations with Robin Friedman and the Gold Country Region go?


Jim McGowan
American Red Cross
312-848-6726 (m)
jim.mcgowan@redcross.org
