### ISSUE TITLE
Determine whether DCSOps access can be provided to a user who does not have an active Volunteer Connection account in a DCSOps-using Region

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#165]
Vineeta John would like user access to DCSOps to conduct SSO testing. Her request:

"As you may know, this week we are testing SSO on ATG Rackspace Production and a few weeks down the line, the same tests will be performed on AEM Stage. The corresponding RCO urls and my user account with SSO ID# are below. Kindly have me set up in DCSO for the 2 systems:
 
I need to have my redcross account (vineeta.john@redcross.org) set up as a dcso login in the following 2 environments:
DCSO Prod pointing to ATG Prod - http://www.redcross.org  - vineeta.john@redcross.org – SSOID# 6549239
DCSO Test pointing to AEM Stage - https://stage-www.redcross.org - vineeta.john@redcross.org - SSOID# 14981681"

**Comment by pjsier** [comment]
@OhMcGoo It's not too difficult to update the admin dashboard to allow for creating users which should give you some more flexibility, and I have that running locally. Otherwise I could add them manually through the application console. Then, once they have an account created, they'll be able to log in at `www.dcsops.org/roster/session/new?legacy=true` with their assigned username and password.

I can add that admin change to the staging site so that you can test it out if that works?

**Comment by pjsier** [comment]
Based off of conversation in the Google Group, closing this now that the user has been created and it's a rare occurrence that's probably not worth adding to the UI @OhMcGoo

**Comment by OhMcGoo** [comment]
Vineeta John can't access DCSOps. Anything additional we may need to do on our end?

**Comment by pjsier** [comment]
@OhMcGoo I'm seeing a login for that user using the RCO ID that I think was after you sent this. Is this still an issue? Otherwise I can keep looking

**Comment by OhMcGoo** [comment]
Can you send me a screenshot of what you see?

**Comment by pjsier** [comment]
@OhMcGoo it's mostly in the logs, and I don't want to accidentally include anything sensitive, but here's the information that seems relevant:

At June 8, 1:13pm CST
`#<OmniAuth::AuthHash email="vineeta.john@redcross.org" sub="6549239">`

And the `last_login` for the user I created with that RCO ID is the same time (1:13pm CST on June 8th). Not sure if you used the admin login as user functionality to test that, but the OmniAuth logs make me thing that's not the case
