### ISSUE TITLE
Make changes to the Damage Assessment section to reflect the Red Cross' current Direct Client Assistance (DCA) model

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#173]
On the **Details** tab of incident reports, make the following changes to the Damage Assessment section:

1. Add **Multi-family home** to the Structure type* pop-up menu between Single family home and Apartment;
2. Change the units fields from Units destroyed*, Units major*, Units minor* and Units affected* to **Units not livable*** and **Units livable***. 

<img width="629" alt="damage assessment" src="https://user-images.githubusercontent.com/4147733/49312871-2741aa80-f4ab-11e8-8513-a2f6e4250de6.png">

**Comment by pjsier** [comment]
@OhMcGoo 1. here is straightforward, but I have some questions for 2. How should we handle existing data here, since it doesn't sound like the new definitions map cleanly onto the old ones? Should we show the make the current fields read-only so that they're still visible on older incidents?

**Comment by OhMcGoo** [comment]
@pjsier: Regarding 2., what if we first insert **Units not livable** and **Units livable** as two additional fields (above Units destroyed) and make them mandatory while making the others no longer mandatory? Once regions have transitioned to using the new designations (say, after a month), we can make the old designations read only. I'm thinking about how we transition as incident reports can often be worked on for up to 2-3 weeks.

**Comment by kfogel** [comment]
Decided w/ @OhMcGoo: Every region is going to make the switch to these new damage classifications, "Units not liveable" and "Units livable".  Howevre, the old data still has to be retrievable.

**Comment by frankduncan** [comment]
Coming up to speed on this.

What do we think about setting adding in a check that says if the incident date is newer than July 1, 2020, do not present the old fields in the edit interface.  Then, in a month (or whatever grace period is needed), we remove the check and remove the old ones completely?

Then, for display purposes, if we see values in the old columns, we display the old values.  If we don't see any, we display only the new data (which could be zero)?

**Comment by OhMcGoo** [comment]
Perfect!

**Comment by kfogel** [comment]
See [branch 173-damage-assessment](https://github.com/redcross/arcdata/tree/173-damage-assessment), and also [these meeting notes](https://github.com/redcross/arcdata/wiki/Meeting-Notes#2020-06-22-430pm-et-frank--jim-meeting-about-dispatch-console).

**Comment by OhMcGoo** [comment]
Please hold off on this change. NHQ is making changes to damage assessment classifications.

**Comment by OhMcGoo** [comment]
Damage assessment classifications are going to remain as-is (Destroyed, Major, Minor and Affected). It is likely that a new classification will be added (Uninhabitable) later this fall but that is still TBD. I am closing this issue.

**Comment by kfogel** [comment]
Note that in our [2020-11-30 meeting](https://github.com/redcross/arcdata/wiki/Meeting-Notes#2020-11-30-4pm-et-regular-check-in-meeting), Clara Walker noted that this issue might need to be reopened, as new damage assessment classifications may be coming out as part of the move to RC Care.
