### ISSUE TITLE
Make changes to the section titles and checkbox items in the incident reports' Assistance Provided window

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#174]
Change _Client Financial Assistance_ to **Direct Client Assistance**

Under **Direct Client Assistance**, rename _Emergency Housing_ to **Lodging**.
Under **Direct Client Assistance**, remove:
- _Food_
- _Clothing_
- _Medication_

Under **Direct Client Assistance**, add:  **Immediate**
Under **Direct Client Assistance**, move  **None** under _Immediate_

Under **Other Assistance**, add: **Health Services** (list above Mental Health)
Under **Other Assistance**, change _Mental Health Support_ to **Mental Health**
Under **Other Assistance**, remove: Snacks for Clients
Under **Other Assistance**, move  **Translation** under _Spiritual Care_

<img width="629" alt="screen shot 2018-11-30 at 2 25 13 pm" src="https://user-images.githubusercontent.com/4147733/49314690-cddc7a00-f4b0-11e8-9aac-af3e0e38e6a3.png">

**Comment by OhMcGoo** [comment]
@pjsier: Can we make one quick change before we tackle this issue more significantly? Simply change **Medication** to **Health Services**. This will satisfy a number of complaints we're receiving from our HIPPA-concerned Disaster Health Services team.

**Comment by pjsier** [comment]
@OhMcGoo This is actually resolved in PR #180. Will merge that now and deploy it
