### ISSUE TITLE
User gets error message when sending text messages to DCSOps

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#182]
When texting with DCSOps, user Tanya Toribio gets the following reply any time she attempts to send a message to the application:

"A person with this phone number was not found in the database."

**In addition, her replies do not appear in DCSOps incident reports as incoming messages.**

**Comment by pjsier** [comment]
@OhMcGoo it looks like the required phone number format DCSOps is checking for is "XXX-XXX-XXXX" and the user's phone was saved as "XXXXXXXXXX". I updated the phone number format so it should work for her now

**Comment by OhMcGoo** [comment]
Thank you, Patrick . . . Will this now work for all unformatted numbers or should I ask our Volunteer Services team to be diligent about how they enter phone numbers in Volunteer Connection?


Jim McGowan
American Red Cross
312-848-6726 (m)
jim.mcgowan@redcross.org
On Apr 25, 2019, 9:26 AM -0500, Patrick Sier <notifications@github.com>, wrote:

@OhMcGoo<https://github.com/OhMcGoo> it looks like the required phone number format DCSOps is checking for is "XXX-XXX-XXXX" and the user's phone was saved as "XXXXXXXXXX". I updated the phone number format so it should work for her now

**Comment by OhMcGoo** [comment]
For now people might need to be careful about how they enter info into
Volunteer Connection, I didn't change any code for this update. I'm
guessing Volunteer Connection has some validation by default though and
this might have been imported separately because otherwise this issue would
be a lot more common
