### ISSUE TITLE
On the the Contact Info button, add the phrase "Text messaging not enabled" to encourage volunteers to set their mobile phone preferences.

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#189]
Phrase will disappear once the preferences have been set for the first time.﻿

**Comment by kfogel** [comment]
On the front page, the "My Contact Info" bar should show "Text messaging not yet enabled" (or something like that) in red to indicate that there is something that needs to be done.  From front page, one goes to Contact Info to set one's Contact Settings, near the bottom.

(See also related issue #190.)
