### ISSUE TITLE
Move Contact Settings up under Contact Info to increase visibility

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#190]
<img width="1280" alt="contact info" src="https://user-images.githubusercontent.com/4147733/65615205-9595b300-df7e-11e9-90e3-f704794ef9f8.png">

**Comment by frankduncan** [comment]
This causes a few newlines to appear under call seetings and carrier settings because the panel is now squeezed, but that should be ok.

**Comment by OhMcGoo** [comment]
@frankduncan I assume I will be able to see this when it gets pushed to staging.

**Comment by frankduncan** [comment]
@OhMcGoo Yep!
