### ISSUE TITLE
Change wording of Contact Settings message

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#191]
New:
_If you would like to receive shift and dispatch notifications and communicate with your Dispatcher/Duty Officer by text:
1. Identify your preferred phone number
2. Select your provider under SMS/Carrier Settings
3. Select Call this number for disasters under Call Settings._﻿

**Comment by frankduncan** [comment]
This replaces

These settings affect how various Disaster systems will contact you. If you have chosen to receive shift notifications by text, those messages will be sent to any phones that you have selected a carrier for below. For dispatch, and calldown, calls will be made in the order you see under "Preferred Contact Order" above. To remove a number, for instance a work phone that is not useful for reaching you in a disaster, change "Call Settings" below to read "Don't call this number." 

Right?

**Comment by OhMcGoo** [comment]
@frankduncan: Yup.
