### ISSUE TITLE
After clicking Submit Incident Report on the main Incidents page, bypass the Currently Open Incidents page and go directly to the Create Incident page

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#198]

**Comment by kfogel** [comment]
I think the "Currently Open Incidents" page is `incidents/CHAPTER_SHORTNAME/incident/activity`.  (Having the full URL in this issue would be great, though.)

**Comment by frankduncan** [comment]
@OhMcGoo  I believe this is the only way to get to the "Currently Open Incidents" page.  Should we just blow that page away as part of this change, or provide a different link to it on that root page?

**Comment by OhMcGoo** [comment]
@frankduncan: I think we're starting to find that there are a handful of pages that, while helpful to me (and perhaps other future administrators), don't need to be a part of the normal workflow. Does it make sense to create a simple Admin page where all these links _live?_

**Comment by frankduncan** [comment]
I think what makes more sense is to have those links in the appropriate places, but with a `if region_admin` check to display them.  So for this one, we'd create a new link to "Currently Active Incidents" right below "Submit Incident Report" but that link only shows up for admins, or whatever permissions level you think is appropriate for viewing that page.

**Comment by OhMcGoo** [comment]
Love it!
