### ISSUE TITLE
Create a way for closing open incident reports listed on the Currently Open Incidents page without having to complete all mandatory fields

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#201]

**Comment by kfogel** [comment]
Just give super-users (like @OhMcGoo) the option to close an incident without all the mandatory fields having been filled out, and it would still count as a responded-to (i.e., completed) incident.

Actually, make this a capability that can be assigned to any role.

Please note that on https://dcsops.org/scheduler/admin/roles, the word "roles" really means "capabilities" and the word "positions" really means "roles" :-).  See also issue #185.

**Comment by kfogel** [comment]
I think the "Currently Open Incidents" page is `incidents/CHAPTER_SHORTNAME/incident/activity`.  (Having the full URL in this issue would be great, though.)

**Comment by frankduncan** [comment]
Creating a way seems straightforward.  Where in the UI should it go?  One option is that when "Close/Submit" there is an option at the top of the page that says "Close without completing" for certain users.

Another option would be on the incident page, before you hit "Close/Submit" there's a button next to "Close/Submit" that is "Close/Submit Incomplete".

A third option is that when you go through the "Close / Submit" and then you get to the final tab "Services" and click "Submit Incident Information" and you have there permissions, it just always submits even if incomplete.

What is the best workflow, or is there a different workflow that's even better?

**Comment by frankduncan** [comment]
I should @OhMcGoo on this question (We can also have a call to discuss more directly)

**Comment by OhMcGoo** [comment]
@frankduncan: I read this last night and have been thinking about what makes the most sense. I like option 1 and tying it to a capability/role (or creating a new role).

**Comment by frankduncan** [comment]
As a part of this, we're going to make the incident number on the Currently Open Incidents page a link to the incident to allow Jim to quickly work through old issues.
