### ISSUE TITLE
In the Attachments section, increase the file size capacity

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#204]

**Comment by kfogel** [comment]
We need to know what the current file size cap is, and then @OhMcGoo will decide what the new cap should be.

**Comment by frankduncan** [comment]
The cap seems to be 2 megabytes.  What do we want it to be?

**Comment by frankduncan** [comment]
The relevant code is in app/models/incidents/attachment.rb:7

**Comment by frankduncan** [comment]
@OhMcGoo ^^

**Comment by OhMcGoo** [comment]
@frankduncan: Let’s do 5MB?
