### ISSUE TITLE
Add a Shift Notes link (https://www.dcsops.org/scheduler/shift_notes) to the DAT Scheduling page

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#207]
https://www.dcsops.org/scheduler/shift_notes

**Comment by frankduncan** [comment]
I'm using the 'sticky-note' fontawesome icon for this one, and putting it right below "Manage Calendars" and making it available for all, since there's permissions checks within the page about adding/editing them.

All sound good?

**Comment by OhMcGoo** [comment]
@frankduncan: For now, yes. I will have to check to see how the Greater New York Region likes it as they are the primary user of that page.

**Comment by OhMcGoo** [comment]
@frankduncan Can you send me a screenshot of what this looks like now?

**Comment by frankduncan** [comment]
The font awesome should show up once we are done with the rails upgrade.
![shift_notes_link](https://user-images.githubusercontent.com/5125316/86542795-8d3fb080-bede-11ea-8963-0e74be7648f8.png)

**Comment by OhMcGoo** [comment]
A screenshot of the button placement on your machine would be helpful.

**Comment by frankduncan** [comment]
Small scope creep:

Create a "Current Shift Notes" link on the responder console that pops up a modal that shows any shift notes for the current day (and only shows shift notes for ones filled in)

Make it say "No Shift Notes" if there are none.
