### ISSUE TITLE
On the main Incidents page, for Recent Incidents, display the street name between the city and incident number

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#208]

**Comment by kfogel** [comment]
The problem we're solving here is that you get eight incidents in a row showing just "Chicago", "Chicago", "Chicago", etc, with nothing else to distinguish them except their incident numbers.  Showing the street name will give a human enough to immediately distinguish one incident from another in a listing of multiple incidents.

**Comment by frankduncan** [comment]
This is actually a duplicate of #143, so going to do the work over there.
