### ISSUE TITLE
Change the NorCen Dispatch Console homepage link so that users bypass the NorCen Dispatch DAT Incidents and Disaster Dispatch/New Incident page and land on the Dispatch New Incident page where they can immediately start creating a new incident

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#209]

**Comment by kfogel** [comment]
This is similar to issue #198.  Here's the deal:

On the NorCen Dispatch Console page (which is linked to from the very front page of DCSOps, and that link links to https://www.dcsops.org/incidents/norcen_dispatch), when you click on "Dispatch Console", it currently takes you to "Disaster Dispatch" (https://www.dcsops.org/incidents/norcen_dispatch/dispatch), and from there you would have to click on "New Incident" to go to https://www.dcsops.org/incidents/dispatch_intake/new .

On the first page, add a "New Incident" button above the current "Dispatch Console" button.  The new button would skip the intermediary and goes directly from the first to the third.

**Comment by kfogel** [comment]
Compare with issue #198.

**Comment by frankduncan** [comment]
I'm also removing the "New Incident" button from the console page just for cleanliness sake, but happy to be overridden on that.

**Comment by OhMcGoo** [comment]
@frankduncan: Fine by me.
