### ISSUE TITLE
On the NorCen Dispatch DAT Incidents page remove the 19-1906 Scott City, KS 1521 Myrtle St incident from the top of the Recent Incidents

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#210]
The incident report was created shortly before midnight on 12/31/18 and concluded on 1/1/19.

**Comment by kfogel** [comment]
Closing this issue.  This incident was started in 2018 and concluded in 2019, which meant it kept staying at the top of lists, until it mysteriously disappeared.

There is, obviously, still some kind of date sorting problem going on, and if so it will show up again the next time there's an incident that is started in one year and carries over into the next year.  If that happens, we'll solve it then.
