### ISSUE TITLE
On the Disaster Dispatch page accessed via clicking the NorCen Dispatch Console homepage button and then the Dispatch Console button, create a way to delete the incidents listed under the Dispatching Incidents heading

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#211]

**Comment by kfogel** [comment]
This is complex.  It will require further conversation with @OhMcGoo to determine exactly what the behavior should be -- maybe not just on https://www.dcsops.org/incidents/norcen_dispatch/dispatch.  We'll need to think more about the workflow.

**Comment by kfogel** [comment]
From discussion with @OhMcGoo: super-admin should have the ability to de-list/close an incident even though that incident might not have all the required fields filled out.

**Comment by frankduncan** [comment]
@OhMcGoo Right now this is all incidents that have not been dispatched.  A further way to limit the list is to only list incidents that are not 'closed' or 'invalid' that have not been dispatched.  Would that be an effective enough way to remove them from the list?  Or is there a reason why closed/invalid incidents would still need to be dispatched?

In development (using the prod db), this reduced the list in norcen from Very Very Long to like 20 current incidents.

**Comment by OhMcGoo** [comment]
In Dispatch Console, change the 'Show' links to read 'Dispatch' and **bold** the text. Move the **Actions** column in between the **Address** and **Status** columns.

**Comment by frankduncan** [comment]
Not quite done.  Once the "Incident Dispatched" timeline entry has been entered into an incident report, it can be removed from the list.
