### ISSUE TITLE
Fix the "Current Activity" link.

### ISSUE THREAD

**Issue by kfogel** [redcross/arcdata#224]
Wish I had the full URL to that link -- @OhMcGoo has it, though.  I think it's different from "Currently Open Incidents" (`incidents/CHAPTER_SHORTNAME/incident/activity`).

There's such a long wait time right now that apparently even Jim has never seen the inside of this chamber in the temple.

**Comment by frankduncan** [comment]
Did some research.  When running in development, this returns (using a copy of a production database).  Not extremely fast, but it is returning a page.  There doesn't look to be anything too egregious in the sql query.  Then, when updating the log level in production so I can see what queries are happening and which one is taking so long, it started returning results there too.

This needs more looking into, but it's looking less like a software problem and more like a server problem.

**Comment by frankduncan** [comment]
Adding an index did improve the slowest query in development by a factor of 1000, so that hopefully that will be enough to make production snappy.  Will need to take a look when this fix makes its way there.

**Comment by OhMcGoo** [comment]
OK, thanks @frankduncan. I'm still not quite sure how the _Current Activity_ feature will get used operationally but I sense it will be really useful for DAT Managers who want to see what's going on without having to open individual incident reports.
