### ISSUE TITLE
Distinguish between manual and scripted for "Submit Incident Report".

### ISSUE THREAD

**Issue by kfogel** [redcross/arcdata#225]
Expand the "Submit Incident Report" button to two buttons:

* "Submit Incident Report: Manually" (the unscripted version)
* "Submit Incident Report: Dispatch Console" (the scripted version)

**Comment by frankduncan** [comment]
After having a conversation with @OhMcGoo, this is enhanced slightly.  For all regions that have the dispatch console enabled, the buttons at the top will be:

* "Dispatch New Incident"
* "Create Incident Reprot"
* "Dispatch Console"

This is related to #209, where those the Dispatch New Incident / Dispatch Console were separated.

**Comment by frankduncan** [comment]
When this is pushed to production, this will require updating the positions to add scope permissions for `dispatch_console` to the right scopes.  We can also make the call to remove scoping from the `dispatch_console` permission and you just have it for all scopes you can see if you have that capability.

**Comment by OhMcGoo** [comment]
@frankduncan: I believe only Illinois and Greater New York will be using the Dispatch Console so I think we will simply need to update the positions and scope permissions for those two regions.

**Comment by frankduncan** [comment]
@OhMcGoo Collateral damage from this is that you can no longer enter the dispatch console from the `norcen_dispatch` place.  Do we care about that?  Maybe just renaming it to "norcen" since you really just go there to look at the whole scope, rather than creating incidents in it.

**Comment by OhMcGoo** [comment]
That's fine as long as we can ensure that the Greater New York Region can dispatch incidents for New Jersey.

**Comment by frankduncan** [comment]
We'll want to test that in staging, but it looks like that capability isn't involved in this.
