### ISSUE TITLE
On admin MOTD, use "All Regions" (instead of blank) for global message.

### ISSUE THREAD

**Issue by kfogel** [redcross/arcdata#254]
On the Message Of The Day (MOTD) admin page, the top choice is a blank entry that actually means "all regions".  Change the blank entry's title to "All Regions", so it's clear what it does.

/CC @OhMcGoo.

**Comment by frankduncan** [comment]
Want this on the Work Plan for FY 21?

**Comment by OhMcGoo** [comment]
@frankduncan @kfogel If it's an Extra Small change, then yes. If it's more work, then no.

**Comment by kfogel** [comment]
Yes if anywhere between Tiny and Small.  It should go on the Work Plan, but be clearly marked as something that wasn't in the either the original FY20 or FY21 contracts.  These are fixed-price contracts: we can do extra work if we want and it's on us, but when we do I want to make it clear that that's what's happening :-).

**Comment by frankduncan** [comment]
It turned out to be less than tiny.
