### ISSUE TITLE
Write scripts from Red Cross-provided spreadsheets and import regional configuration data into DCSOps

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#255]
Write scripts from Red Cross-provided spreadsheets and import regional configuration data (including response and shift territories, positions, shifts, shift times, etc.) into DCSOps.

**Comment by OhMcGoo** [comment]
The spreadsheets can be found [here](https://americanredcross-my.sharepoint.com/personal/jim_mcgowan_redcross_org/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjim%5Fmcgowan%5Fredcross%5Forg%2FDocuments%2FDCSOps%20Regional%20Configurations&originalPath=aHR0cHM6Ly9hbWVyaWNhbnJlZGNyb3NzLW15LnNoYXJlcG9pbnQuY29tLzpmOi9nL3BlcnNvbmFsL2ppbV9tY2dvd2FuX3JlZGNyb3NzX29yZy9FckRHV25YOE1OQkR0NURUZHZPSFNzZ0JPTnRnMVB0eHU4ZDlCamM2YmU1aUR3P3J0aW1lPTVkZ0FkdVVpMkVn).

**Comment by OhMcGoo** [comment]
@frankduncan, @kfogel: DCSOps Configuration spreadsheets are 85-95% complete. Response Territories, Shift Territories, Positions, Shifts and Shift Times are 99% complete. Regions are working to finalize Capabilities, Dispatch Configurations (if used) and Notifications. I've given Regions a deadline of Thursday, COB to have all corrections/updates to me. This way I can have everything completed by Friday. After that, no changes.

**Comment by kfogel** [comment]
@frankduncan has all the spreadsheets now, right @OhMcGoo ?

**Comment by OhMcGoo** [comment]
All are uploaded, however, Greater New York (which I just reposted) still needs some work (it's 90% complete). I can have it done by mid-afternoon.

**Comment by OhMcGoo** [comment]
@frankduncan: When adding the new configurations to DCSOps:

- **Dispatch Configurations**: Ignore the named Backups (first-fourth) and create configurations with only the Shifts,
- **Notifications**: Ignore the Notifications information (in the spreadsheets) and permit what is currently in DCSOps to remain. I will manually rebuild the notifications for each region.

**Comment by frankduncan** [comment]
We are Realigned!!
