### ISSUE TITLE
Hide ‘Team Lead Trainee’ from the Response* pop-up menu

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#261]
Hide ‘Team Lead Trainee’ from the Response* pop-up menu:

![Hide Team Lead Trainee](https://user-images.githubusercontent.com/4147733/88398264-c4d9a400-cd8a-11ea-9f4b-1d84aa4a0859.png)

**Comment by kfogel** [comment]
Estimate: Tiny.  Good for a volunteer.

**Comment by kfogel** [comment]
Tiny.  Good for a volunteer.

**Comment by OhMcGoo** [comment]
@kfogel @frankduncan  Can we push this one into the "Let's do it now" category? In addition to the above, change **Dispatch** to **Dispatcher/Duty Officer**.

**Comment by kfogel** [comment]
Let's do it now then.  While this would have been a beautiful onboarding opportunity for a new contributor, we'll have plenty of those.

**Comment by kfogel** [comment]
Let's do it now then.  While this would have been a beautiful onboarding opportunity for a new contributor, we'll have plenty of those.

**Comment by frankduncan** [comment]
This is in staging now
