### ISSUE TITLE
Permit Shift Categories to be disabled

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#265]
Permit Shift Categories to be disabled (hidden from view).

**Comment by frankduncan** [comment]
Which views?

**Comment by frankduncan** [comment]
@OhMcGoo Answered this in call it's in the "County view" under categories.

**Comment by frankduncan** [comment]
@OhMcGoo This is deployed in staging.

**Comment by OhMcGoo** [comment]
Ooh! Ooh! I can’t wait to see it!
