### ISSUE TITLE
Shift Times do not have Start and End offsets, do not order chronologically in calendar

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#283]
ALL Shift Times created in Staging have a Start offset of "0" (12AM) and an end offset of "1234" (Blank):
![Edit Shift Time](https://user-images.githubusercontent.com/4147733/89216618-536ed200-d590-11ea-81e1-a54f7744c020.png)

Thus, they don't order themselves chronologically (from top to bottom) in the Calendar views:
![August Schedule (Order)](https://user-images.githubusercontent.com/4147733/89216626-59fd4980-d590-11ea-8f63-d5da5e49f66c.png)

nor show scheduled responders in the Responders Console:
![Responders Console](https://user-images.githubusercontent.com/4147733/89216887-d98b1880-d590-11ea-9f7f-6a32e5219cbd.png)

**Comment by frankduncan** [comment]
Right, this was going to be post setup configuration that needed to be done.  Otherwise, we'll need to put the offsets into the spreadsheets.  This is also lumped into question about how to handle "Monday 6AM-Friday 12PM" or whatever that weird edge case was.

**Comment by OhMcGoo** [comment]
Then I feel like the Configuration spreadsheets should reflect the following:

Period
Start offset*
End offset*
Active sunday
Active monday
Active tuesday
Active wednesday
Active thursday
Active friday
Active saturday

Manually configuring EVERY shift group after we launch will take too long (and be extremely tedious).

**Comment by frankduncan** [comment]
Yeah, that's fine.  Some of the sheets have multiple times in one cell, so those will need to be split.  Once the data is updated, it's straightforward to update the importer to pull these values.

**Comment by OhMcGoo** [comment]
@frankduncan: I have modified the Shift Times in the Illinois Configurations spreadsheet (and am now working on others). Take a look and let me know what you think. I also think I've figured out how to manage shifts that span days.

**Comment by OhMcGoo** [comment]
@frankduncan: Shift Times have also been updated for: California Gold Country, Cascades, Idaho and Montana, Kansas, Minnesota and Dakotas, New Jersey and Northern California Coastal. I will get to Greater New York and Nebraska laster today.

**Comment by frankduncan** [comment]
@OhMcGoo Code is written against Illinois and works correctly.  When the rest are done, I'll run it for everyone and put them in staging.

**Comment by OhMcGoo** [comment]
@frankduncan: Working on GNY and Nebraska now.

**Comment by OhMcGoo** [comment]
@frankduncan: GNY and Nebraska are done.

**Comment by frankduncan** [comment]
@OhMcGoo Hm, I didn't catch this before, but now the shift name doesn't match the shifts.  "4PM-6PM" is now a name, but in shifts it's "4PM-6PM (Monday-Friday)".  The day range has been put into Note.  How do we want to handle?

**Comment by frankduncan** [comment]
@OhMcGoo That was for Illinois.

**Comment by OhMcGoo** [comment]
@frankduncan  Let me make some tweaks.

**Comment by OhMcGoo** [comment]
@frankduncan  All **Shift Times** Names are titled properly in the **Shifts** tab of each configuration spreadsheet.

**Comment by frankduncan** [comment]
I believe this is fixed with the spreadsheet updates
