### ISSUE TITLE
Shifts scheduled for specific days of the week are active every day

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#284]
Shifts scheduled for specific days of the week are active every day:
![August Schedule (Active Every Day)](https://user-images.githubusercontent.com/4147733/89217047-25d65880-d591-11ea-83b8-47e52230397f.png)

**Comment by frankduncan** [comment]
Similar to [my comment](https://github.com/redcross/arcdata/issues/283#issuecomment-668187876) on #283

**Comment by frankduncan** [comment]
This is fixed!  Woo!
