### ISSUE TITLE
DCSOps Admin in Cascades can't see the Responders Console

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#286]
When attempting to access the Responder Console from within an incident report (Responders tab > Show Responders Console), a user with DCSOps Admin gets an error (DCSOps - Oh No! (500)) and a blank page: https://arcdata-staging.herokuapp.com/incidents/cascades/incidents/21-114/responders

**Comment by frankduncan** [comment]
So no one can see the responders console.  This is because response territories aren't configured to be linked up to shift territories.  That information isn't in the spreadsheet.

I can just link them if they have a similar name, and there may be no cases where they don't.

**Comment by frankduncan** [comment]
Linking all incidents for all time was taking too long, so I'm just doing it for 2020 incidents.  However, now that they are linked and the response territories are linked, responders console is working.

**Comment by OhMcGoo** [comment]
@frankduncan  Will we need to link ALL the incidents at some point?

**Comment by frankduncan** [comment]
Yes, but only once, when we’re ready to go to production.

**Comment by OhMcGoo** [comment]
Fine with me.
