### ISSUE TITLE
DCSOps Admin in Cascades can't see the Manage Calendars and Show Roster links

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#287]
A DCSOps Admin in Cascades can't see the Manage Calendars and Show Roster links on the DAT Scheduling page:

<img width="1173" alt="DAT Scheduling" src="https://user-images.githubusercontent.com/4147733/89467509-4fcb7e80-d73b-11ea-864d-79c706a4d9e5.png">

**Comment by frankduncan** [comment]
This may have been based on a bad export of the db.  With todays export, when impersonating either admin from cascades, I see those links.

**Comment by OhMcGoo** [comment]
@frankduncan  I think it may have been fixed when we got the Capabilities spelled and cased properly.
