### ISSUE TITLE
Current On-Call Team doesn't appear on DAT Scheduling page; full team doesn't show when clicking 'See all'

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#288]
Current On-Call Team doesn't appear on DAT Scheduling page:

<img width="1271" alt="DAT Scheduling" src="https://user-images.githubusercontent.com/4147733/89467919-19423380-d73c-11ea-967d-cfc3a75f03fe.png">

The full team doesn't show when clicking **See all** (https://arcdata-staging.herokuapp.com/scheduler/on_call).

**Comment by frankduncan** [comment]
This is because I didn't run vc import after realigning.  I have done so and now uploading the correct db, and things will show up after that's done.

**Comment by OhMcGoo** [comment]
@frankduncan  Thanks! So, what determines the order of the Shift Territories?

<img width="347" alt="Current On-Call Team" src="https://user-images.githubusercontent.com/4147733/89649780-eb1d3a80-d886-11ea-9957-fe36df3afe74.png">

**Comment by frankduncan** [comment]
Probably last access time in db.
