### ISSUE TITLE
Provide DCSOPs Admins with access to Roster > Vc Positions in Active Admin

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#289]
Provide DCSOPs Admins with access to Roster > **Vc Positions** in Active Admin.

**Comment by frankduncan** [comment]
Readonly, or edit access as well?

**Comment by frankduncan** [comment]
@OhMcGoo ^^

**Comment by OhMcGoo** [comment]
@frankduncan  Is this something I should understand?

**Comment by OhMcGoo** [comment]
Oh, oops . . . I thought I commented yesterday. Edit access.

**Comment by frankduncan** [comment]
This is fixed in staging (after code is pushed)
