### ISSUE TITLE
Event names not displaying properly in Timeline entries

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#292]
The **Event** names in the Timeline are not displaying properly. Here's Staging:

<img width="590" alt="Add Event - Staging" src="https://user-images.githubusercontent.com/4147733/89562790-23b60900-d7e0-11ea-8698-a04c63a8aed5.png">

Here's Production:

<img width="590" alt="Add Event - Production" src="https://user-images.githubusercontent.com/4147733/89562801-287abd00-d7e0-11ea-9d28-20aef176d012.png">

**Comment by frankduncan** [comment]
This is fixed in staging (as soona s the code is deployed)
