### ISSUE TITLE
When creating an incident (in PRODUCTION), the (Response) Territory is not populating

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#294]
When creating an incident in DCSOps PRODUCTION (https://www.dcsops.org/incidents/cni/incidents/new), the (Response) Territory is not populating automatically:

<img width="600" alt="Create New Incident" src="https://user-images.githubusercontent.com/4147733/89684460-15d7b500-d8c0-11ea-90f1-58a6fe27f569.png">

**Comment by frankduncan** [comment]
It appears to be working in staging.... So fixed?

**Comment by OhMcGoo** [comment]
@frankduncan  Nope . . . Broken in production.

**Comment by frankduncan** [comment]
Do we want me to spend time on this before we push staging to production?  Or just check that it's fixed when we get there?

**Comment by OhMcGoo** [comment]
It should be fixed now assuming it won’t take hours to fix. Any idea how it broke?


Jim McGowan
j.mcg@mac.com
312-918-6290

**Comment by frankduncan** [comment]
No clue how it could have.  Any idea when it broke?  And I'll load up prod into development and see if it happens locally.

**Comment by OhMcGoo** [comment]
I was just alerted to it today.

**Comment by frankduncan** [comment]
Hm, it works in dev after I import the production data.  Try microsoft solution?

**Comment by frankduncan** [comment]
This was getting blocked by WAF.  I've added a whitelist rule for the path doing this request and now things work again.

**Comment by OhMcGoo** [comment]
Damn WAF!

**Comment by OhMcGoo** [comment]
It works! Just dispatched this fire:

![21-0349 Glendale Heights, IL 2101 Oriole Ln](https://user-images.githubusercontent.com/4147733/89707427-6a684800-d933-11ea-8e48-15144ff35619.png)
