### ISSUE TITLE
Users in New Jersey with Submit Incident capability can't create incident reports

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#296]
Users in New Jersey with Submit Incident capability (like Duty Officer) can't create incident reports.

This user . . .

<img width="1279" alt="Contact Info" src="https://user-images.githubusercontent.com/4147733/89712028-c80c8c80-d953-11ea-87d6-995c08c22854.png">

. . . can see only this at https://arcdata-staging.herokuapp.com/incidents/newjersey:

<img width="1279" alt="New Jersey DAT Incidents" src="https://user-images.githubusercontent.com/4147733/89712022-ba570700-d953-11ea-9bd4-6b4b8368febf.png">

**Comment by frankduncan** [comment]
I think this may have been an import problem?  When impersonating this person, I see everything:
![newjersey](https://user-images.githubusercontent.com/5125316/89746626-57af5980-da80-11ea-8a95-0150cb531b77.png)

**Comment by OhMcGoo** [comment]
@frankduncan  I saw that the an incident report was created successfully (by the person you were impersonating) earlier this evening.

I am closing this issue.
