### ISSUE TITLE
When filtering for incidents by County on the More Incidents... page, pop-up menu doesn't display counties

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#298]
When filtering for incidents by County on the More Incidents... page (https://www.dcsops.org/incidents/illinois/incidents), the pop-up menu doesn't display counties. Instead, it simply shows **County**:

<img width="1280" alt="County" src="https://user-images.githubusercontent.com/4147733/90346999-00b30280-dff3-11ea-89b9-4709acdc479f.png">

**Comment by OhMcGoo** [comment]
While the counties show up in the pop-up menu, the selection of a county does not filter incidents when **Search** is clicked.

**Comment by frankduncan** [comment]
Fixed Part 2, however after you select the county, you can't then select a different county since the list of options is based on the incidents returned from the search.  When doing this fix, I'm not sure that this code ever worked in production...

At any rate, it's been deployed.
