### ISSUE TITLE
Export a position with shift hours being sent to Volunteer Connection

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#30]
For Volunteer Connection-recorded hours, NHQ now requires a position to be attached to each record for the hours to be counted towards Regional goals.

<img width="994" alt="position" src="https://cloud.githubusercontent.com/assets/4147733/11509722/5e53df88-9825-11e5-8af8-3d9a9f704442.png">

Attach position data to DCSOps hours exports when transferring to Volunteer Connection.

**Comment by jasonwinget** [comment]
See also the issue opened that you cannot submit larger than 40 hour blocks of time.

**Comment by cecilia-donnelly** [comment]
See #34, as mentioned by @jasonwinget.

**Comment by kfogel** [comment]
Closing because this is really a sub-issue of #34 (as explained by @bnazari on the phone just now); fixing #34 will fix both.
