### ISSUE TITLE
Pricing for Livable assistance is not correct. 

### ISSUE THREAD

**Issue by smille1834** [redcross/arcdata#31]
When editing or creating a client in DCSOps, the cost for livable assistance is incorrect. It should be 50 x quantity. It appears to be 50 x 1, then + 35, then + 20 for each additional client after that. Livable X 4 should equal 200. Right now Livable x 4 equals 115.

**Comment by OhMcGoo** [comment]
The pricelist Type for 'Livable' was marked as **Food** (which was set-up to escalate using the old model: $50 for 1, $75 for 2, $95 for 3, etc.). I have changed the Type to **Default** so it will now count up in increments of $50:

<img width="388" alt="screen shot 2015-12-02 at 3 21 03 pm" src="https://cloud.githubusercontent.com/assets/4147733/11544712/f2151d2a-9908-11e5-92fd-604747101b9e.png">
