### ISSUE TITLE
Clients: show phone number in reading view

### ISSUE THREAD

**Issue by jasonwinget** [redcross/arcdata#46]
The phone number for the client is only visible in edit mode for that client.  Display the phone number field in read only view.  Dispatchers believe everything that is being stored for the client is displayed on the read only view, when it is hidden the data is believed to not exist.  (Review other entities and determine if other items should be also shown.)

**Comment by cecilia-donnelly** [comment]
@OhMcGoo, is this what you fixed in your pull request https://github.com/redcross/arcdata/pull/58, or is this a separate issue?

**Comment by OhMcGoo** [comment]
Yep!
