### ISSUE TITLE
Email: Shift reminder fields not aligned appropriately

### ISSUE THREAD

**Issue by jasonwinget** [redcross/arcdata#53]
The shift reminder email seems to not have the right fields being pulled in.  Same below, names changed to protect the innocent.

----- Forwarded Message ----- 
From: DAT Scheduling scheduling@dcsops.org 
To: Jane Doe jane.doe@gmail.com 
Sent: Wednesday, June 3, 2015 4:02 PM 
Subject: Trainee - TCA North on Jun 04 

Susan: 
This is just a friendly automatic reminder that you have an upcoming Red Cross DAT shift! 
You are signed up as Trainee - TCA North for the 12a-6a shift on Thursday, June 04 from 12:00AM to 6:00AM. 
The lead for your shift is Jane Doe, phone 612-123-4567 or 612-987-1234 
If we get a DAT call-out, Jane will contact you at the following phone numbers: 
Your Phone First: 612-123-4567 
Your Phone Second: 612-987-1234 
Please make sure that you are reachable on one or both of these numbers at all times throughout your shift! Remember that we commit to one-hour response time to a call. If one of these numbers is a cell phone, please keep it with you at all times, with the ringer on and loud enough that you can hear it, and sufficient battery charge to accept the call and last throughout the deployment of the call. 
If your availability changes between now and the end of your shift, or the phone numbers shown above are incorrect, please contact the shift lead as soon as possible. 
Your team for this shift is: 
Trainee - TCA North: Jane Doe, 612-123-4567 (C), 612-987-1234 (H) 
## THANK YOU for your participation on Red Cross DAT! Our work is important and brings comfort and reassurance to people in a time of exceptional need. 

This message is sent by the DCSOps Scheduling System. Edit your notification preferences here: http://www.dcsops.org/scheduler/notification_settings/me

**Comment by cecilia-donnelly** [comment]
@jasonwinget, just to be sure: the problem here is that the shift lead's name and phone number is not being displayed correctly?  Instead, the trainee is being shown her own name and phone numbers?

**Comment by jasonwinget** [comment]
That is correct.  In this case the trainee was leading themselves.  She will contact her self etc.
