### ISSUE TITLE
SMS: recruitment messages lose important data from volunteers

### ISSUE THREAD

**Issue by jasonwinget** [redcross/arcdata#55]
Suggested improvements for the SMS recruitment process from a user in our region:

After a recruitment message is sent, any SMS response received that includes "yes" or "no" anywhere in the body of the message should be trapped as it does now as not available or available. But if there is any additional text in that message, post process it in the same way an unsolicited incoming message would be handled. Put the entire message up on the incidents page for the dispatcher to access.

What is happening now is someone might reply: "yes in 2 hours" or "no but I can in 2 hours" and the important bits are being truncated....especially in the second scenario.

**Comment by cecilia-donnelly** [comment]
@jasonwinget this seems like a great idea.  I just left you a voicemail -- let me know if you have time and want to talk through the issues you've filed in the past few weeks to discuss which ones are highest priority for your region.
