### ISSUE TITLE
Non-Versioned File

### ISSUE THREAD

**Issue by mchu0010** [redcross/arcdata#56]
I'm trying to get arcdata/DCSOps running locally so that I can start fixing some of the bugs. I encountered the following code in the file db/seeds.rb. One of these lines refers to a file that isn't in this repository. 

```
#load "lib/vc_importer.rb"; 
#vc = Roster::VCImporter.new; 
#vc.import_data(Roster::Chapter.first, "/Users/jlaxson/Downloads/LMSync1.xls")
```

I haven't been able to get this project up and running yet, would this file help? If not, should I remove those lines?

**Comment by kfogel** [comment]
I think this is now subsumed in issue #67, so closing this ticket as a _post facto_ duplicate.
