### ISSUE TITLE
Incidents: Move territory choice

### ISSUE THREAD

**Issue by jasonwinget** [redcross/arcdata#62]
The "territory" is displayed in the "location" section.  It cannot be edited by location edit, it has to be edited in the "type of incident" option.  It is a geographic element, not an incident type element, so move the edit of the territory for an incident to the location edit where the user would expect it to be located.

**Comment by Norman-Lee** [comment]
Hey Jason!

I heard about this project about 6 months back when it was at HackIllinois, and was thinking about contributing back then. I've submitted a pull request (#97) , let me know what, if anything needs to be done for me to keep helping out.

-Norman
