### ISSUE TITLE
Include live homepage links in repo?

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/arcdata#74]
The DCSOps homepage links to several outside files and sites.  Some of these seem more private than others.  Should we link to some or all of them from the publicly deployable version of the app?  Most of them are just links to login pages, which seem fine.  Others are manuals or other static files.

**Comment by OhMcGoo** [comment]
What would be the benefits of linking them? Drawbacks?

**Comment by cecilia-donnelly** [comment]
@OhMcGoo hey!  @kfogel may have other notes, but I would say that the benefits are to make the dev version as close as possible to the live version and to show developers user manuals, for example.  The only drawback would be if some of these links are secret and we expose them in the repository.  Essentially, if we don't have any reason to keep the links secret then we ought to include them in the repo.  If we don't include them then we need to have some way to manage the fact that the dev version and live version have diverged here.

**Comment by OhMcGoo** [comment]
@cecilia-donnelly:
Here's what should and should not be shared:

**Other Tools**
Volunteer Connection - Requires credentials to access site

**Dispatch**
NorCen Dispatch Console - OK
Dispatcher Updates - Do not share link
Fire Department Contacts - Do not share link
CAS 2.0 - Requires credentials to access site
Dispatch Mini-Manual - Do not share file
Chicago and Northwest Illinois Region Map - OK to share

**Admin / Staff Back-Up**
Response Handbook - Do not share file

**SitCell**
SitCell Common Operating Picture - Requires credentials to access site

**Help**
DCSOps Training Videos - OK to link URL

**Comment by cecilia-donnelly** [comment]
@OhMcGoo,
Great, thank you!  I'll update accordingly.

**Comment by jasonwinget** [comment]
Won't each of the "chapters" have individual links that need to be verified?  Can we simply scramble URL to protect the content on those?  It breaks the loading of the content but the buttons would still be there in dev.

**Comment by kfogel** [comment]
@jasonwinget Something like that.  More likely we'd just have them all link to a dedicated page (a new static page that we'd create in the application) that explains why the link went here instead of to the expected information.

**Comment by jasonwinget** [comment]
Karl, agreed I had thought of that later too.

**Comment by kfogel** [comment]
Cool -- glad it sounds reasonable to you too.
