### ISSUE TITLE
Create default calendar view for shift scheduling

### ISSUE THREAD

**Issue by mmcneill** [redcross/arcdata#82]
This issue is part of a broader set of features related to improving the shift scheduling process.  See docs/DCSOps_Functional_Specification.pdf  (#81)  for background information and details.  

When a volunteer lands on the initial “DAT Scheduling” page, they should see a monthly calendar view with shifts specific to their position and only one default region.  Currently, the calendar that appears includes shifts for the volunteer’s positions in all regions.  By focusing in on one region, the goal is both to immediately point the volunteer to the region with the most need and to display a less cluttered, confusing calendar view.  
The volunteer can navigate to calendars for other regions for which they are registered through a set of menu tabs (i.e. the calendar below belongs to a volunteer registered in Chicago, Greater Cook, and Southwest Suburbs only).  Additionally, there should be a tab for All Regions that shows shifts for all of the regions in which the volunteer is registered (similar to DCSOps’ current My Positions view).

![req1](https://cloud.githubusercontent.com/assets/5384790/13828664/a07ea6cc-eb90-11e5-9665-3b167b18d9b1.png)

The “default” calendar for a given volunteer is determined by the incident frequency of the regions for which the volunteer is registered.  The general order of incident frequency in regions handled by the American Red Cross of Greater Chicago is as follows: Chicago > Greater Cook > Southwest Suburbs > Northwest Indiana.  Therefore, if a volunteer is only registered for incidents in Greater Cook and Southwest Suburbs, their default region is Greater Cook.  For now, this order is static and does not depend on predicted number of incidents or lack of schedule coverage at that specific time.

**Comment by cecilia-donnelly** [comment]
I believe the current calendar can be found at `/scheduler/calendar/2016/march` or more generally `/scheduler/calendar/<year>/<month>`.  You can find it by clicking on DAT Scheduler in the top menu, then clicking "County Schedule" under one of the months in the middle column of that page.

For the code, I think we can start by looking at `app/controllers/scheduler/calendar_controller.rb`.

@mmcneill, is that the page you were referring to when you mentioned the current calendar?  Is that where these changes should be made?

**Comment by mmcneill** [comment]
@cecilia-donnelly yes, that is the correct page (and controller) I was referring to.  Note that this county specific calendar can also be accessed by clicking DAT Scheduling (top bar) > Sign Up (under any of the visible months) > County Shifts.  No matter which way the county specific calendar is accessed, the shifts for the default region should be loaded automatically (instead of loading a blank calendar as it does now).
