### ISSUE TITLE
Add shift recommendation feature

### ISSUE THREAD

**Issue by mmcneill** [redcross/arcdata#84]
This issue is part of a broader set of features related to improving the shift scheduling process. See docs/DCSOps_Functional_Specification.pdf  (#81)  for background information and details.

Volunteers in DAT positions (Lead, Responder, or Trainee) should have the option of clicking a “Suggest shifts” button that highlights 5 recommended shifts over the next 30 days.  Recommended shifts are a combination of those most in need of volunteers and those in which the volunteer has had successful responses in the past (formula below).  The classification of shifts as “in need” is a function of expected number of incidents in that shift and number of volunteers already signed up for that shift.

![req3_1](https://cloud.githubusercontent.com/assets/5384790/13828986/8c18ae10-eb92-11e5-942a-5f31a926e9d0.png)

When utilizing the shift recommendation tool, the volunteer should be automatically jumped to the “All Regions” tab of the calendar.  Note that because shift recommendations can be for any shift over the next 30 days and it is best for all recommendations to appear on the same screen, it is likely necessary for 2 calendar months to be displayed on the same page when this feature is in use (normally only one month is displayed at a time).  

When the “Suggest shifts” button is clicked, a recommendation score will be calculated for each unique shift of the next 30 days.  The shifts with the top 5 recommendation scores should then be highlighted on the calendar.  The volunteer should then have the option of clicking a “Show 5 more” button, a “Hide suggestions” button, or signing up for a shift directly from this screen like they normally would.

A “unique shift” here is really a region/day/time block combination, so the total number of unique shifts for the next 30 days is equal to 30 days \* 6 time blocks per day \* # of regions for which the volunteer is registered.  Note that all of the metrics defined below correspond to unique shifts (defined at the region/day/time block level).  

![req3_2](https://cloud.githubusercontent.com/assets/5384790/13829211/ca237bbc-eb93-11e5-9de2-9768b1b3269e.png)

The various components of this formula are further defined below.  

Appropriate values for the “Newness” parameter can be found in the table below.  An opportunity to respond is defined as a call from dispatch while on the schedule (regardless of whether the volunteer accepted or declined the incident).  This opportunity has nothing to do with the unique shift being evaluated, but is a broad measure of how new the volunteer is to DAT response.  

![req3_3](https://cloud.githubusercontent.com/assets/5384790/13829213/ce51859e-eb93-11e5-86e5-9df1567ecba0.png)

Here, Total Calls is the number of calls that the dispatcher made to volunteers during a shift in an effort to staff an incident.  Note that this Shift Response Rate metric is not related to a specific volunteer, but all volunteers who were called during that shift. 

![req3_4](https://cloud.githubusercontent.com/assets/5384790/13829241/ef0e001e-eb93-11e5-86ee-ac64930dcb06.png)

Accept.Prop and Decline.Prop refer to the proportion of a volunteer’s accepted opportunities and declined opportunities, respectively, that occur under the conditions of the subscript.  Subscript R means region, subscript DT means day/time block, and subscript RDT means region/day/time block.  For example, Accept.Prop<sub>RDT</sub> is the proportion of the volunteer’s accepted opportunities that occur in the same region/day/time block as the shift being scored.  Similarly, Decline.Prop<sub>R</sub> is the proportion of the volunteer’s declined opportunities that occur in the same Region as the shift being scored.  Note, not answering the phone when on the schedule counts as declining.

**Comment by cecilia-donnelly** [comment]
@mmcneill, just to clarify: "the volunteer has had successful responses" means that the volunteer was dispatched, right?  That is, they were signed up, an incident occurs, and they actually went to the scene?

**Comment by mmcneill** [comment]
@cecilia-donnelly correct!

**Comment by cecilia-donnelly** [comment]
In order to do this, we need to know:
- `Need:VolunteersSignedUp`: number of people currently signed up for each future shift
- `Need:TargetVolunteers:ExpectedNumberOfIncidents`: average number of incidents in this unique shift in the last 12 months
  - this implies that either each incident should be associated with a shift or that we should be calculating the shift match based on the region, day, and time for the incident.
- `Need:TargetVolunteers:ShiftResponseRate:TotalCalls`: total calls made by the dispatcher in this shift (where are these stored?)
- `Need:TargetVolunteers:ShiftResponseRate:CallsWithPositiveResponse`: positive responses to the dispatcher in this shift
- `Newness:OpportunitiesToResponse`: total incidents in the logged-in user's past shifts 
- `PastAccepts` and `PastDeclines`: number of past accepts and declines for logged-in user
  - where are these stored?

**Comment by mmcneill** [comment]
@cecilia-donnelly I believe the data for PastAccepts and PastDeclines can be taken from the "role" variable in the "incidents_responder_assignments" table.  For each incident for each person called, this variable has values like "no_answer" and "not_available" indicating declines and values like "responder" and "team_lead" indicating accepts.

**Comment by cecilia-donnelly** [comment]
@mmcneill perfect, thank you!  I see now that we can find in that table all the times a person was contacted and their role each time.

**Comment by mmcneill** [comment]
Here is a google doc to use at the hackathon for collaboration:
https://docs.google.com/document/d/15YgrX8OLq-AHujspPWzvhokUu660fLiWgvVWQxjQX6U/edit?usp=sharing
