### ISSUE TITLE
Add informative icons to incident dispatch view

### ISSUE THREAD

**Issue by mmcneill** [redcross/arcdata#85]
This issue is part of a broader set of features related to improving the incident dispatch process. See docs/DCSOps_Functional_Specification.pdf (#81) for background information and details.

When choosing from the list of possible responders on the incident dispatching portal, the dispatcher should be able to see icons next to each volunteer's name that give useful information about the volunteer's desire and likeliness to respond to the incident.   The three icons suggested below are the "Pick Me!" icon, the "Not Likely" icon, and the "Super Reliable" icon.  

The "Pick Me!" icon should appear next to the names of volunteers who really want to get called to respond.  This feature will hopefully help to balance out the number of opportunities given to the small group of “engaged” volunteers and the large group who never get called.  Whether or not a volunteer has an icon next to their name is based on a setting the volunteer chooses when signing up for shifts (#86).  This feature only applies to the official schedule (not the flex schedule).

![icons](https://cloud.githubusercontent.com/assets/5384790/13829873/56444524-eb97-11e5-9f7f-1db2ad32f404.png)

![req4](https://cloud.githubusercontent.com/assets/5384790/13829804/e7bdbe1e-eb96-11e5-8dbc-6e72df849817.png)

The "Not Likely" icon should appear next to the names of volunteers who have an extremely low response rate (based on the last 10 calls).  This feature will hopefully help dispatchers avoid wasting time when they are really in a hurry to staff an incident.  Additionally, this will inform the Red Cross of volunteers who are likely better suited for different non-DAT roles.  A volunteer qualifies for this icon if they have been given at least 10 opportunities to respond and have declined (or not answered the phone) the last 7 times in a row. 

This feature applies to both the official schedule and the flex schedule, but the decision to mark someone as “Not Likely” is only based on their response history for the schedule they are currently on.  

![req5](https://cloud.githubusercontent.com/assets/5384790/13829935/adc1017a-eb97-11e5-8b38-219bd906bd0b.png)

For example, if a volunteer has a perfect response rate on the official schedule but has declined 50 opportunities in a row on the flex schedule, the volunteer only gets a “Not Likely” icon by their name when they are on the flex schedule.

A volunteer should have the “Super Reliable” icon next to their name if they have been given at least 20 opportunities to respond and have declined (or not answered the phone) less than 10% of the time.

![req6](https://cloud.githubusercontent.com/assets/5384790/13829928/a7c1923a-eb97-11e5-90ce-27c1a654ab38.png)

Again, this feature applies to both the official schedule and the flex schedule, but the decision to mark someone as “Super Reliable” is only based on their response history for the schedule they are currently on.

**Comment by cecilia-donnelly** [comment]
I believe this refers to the  `/incidents/arcil/incidents/<incident_number>/responders` page.

The "Not Likely" and "Super Reliable" metrics will rely on the same information we look for in #84 for `Past Accepts` and `Past Declines`.

**Comment by jasonwinget** [comment]
This should be something that can be turned on and off by each "chapter" in the system.  I can see some chapters wanting and some not wanting this feature.
