### ISSUE TITLE
Add ability for volunteers to inform dispatchers that they really want to respond (Pick Me!) 

### ISSUE THREAD

**Issue by mmcneill** [redcross/arcdata#86]
This issue is part of a broader set of features related to improving scheduling and the incident dispatch process. See docs/DCSOps_Functional_Specification.pdf (#81) for background information and details.

See issue #85 for related features.  

When a volunteer signs up for a given shift, they should have the option of marking themselves with the “Pick Me!” icon for that shift so they are more likely to be called during an incident.  This hopefully will be a good way for newer, more under-engaged volunteers to get an opportunity to get involved.  

To make this possible, there needs to be a basic button or link on the DAT Scheduling main screen (the view with Personal Details, Calendar Details, Current On-Call Team, etc.) that, when clicked, leads to a page that list the shifts for which the volunteer is currently signed up.  On this page, they can select the “Pick Me!” icon next to a shift.  When a reminder is sent out to a volunteer about an upcoming shift, there should be a link to this page to remind volunteers of the “Pick Me!” option.  

![pickmesetting](https://cloud.githubusercontent.com/assets/5384790/13830164/eee8b804-eb98-11e5-9add-f04da05ed96a.png)

**Comment by cecilia-donnelly** [comment]
This is a prerequisite for part of #85.  The volunteer needs to be able to indicate "Pick Me!" before the "Pick Me!" icon can show up on the dispatcher's list of volunteers.

**Comment by cecilia-donnelly** [comment]
I think the new "My Upcoming Shifts" button can link to the existing `app/views/scheduler/shift_assignments/index.html.haml` page, with a new column for the "Pick Me!" icon.

**Comment by jasonwinget** [comment]
This should be something that can be turned on and off by each "chapter" in the system. I can see some chapters wanting and some not wanting this feature.
