### ISSUE TITLE
Store data related to new features (shift recommender and incident dispatching icons)

### ISSUE THREAD

**Issue by mmcneill** [redcross/arcdata#87]
This issue is part of a broader set of proposed features related to improving scheduling and the incident dispatch process. See docs/DCSOps_Functional_Specification.pdf (#81) for background information and details.

Once volunteers have the option of receiving shift recommendations (#84), it is very important for the Red Cross to have the ability to measure the effect this feature has on volunteer engagement and schedule coverage overall.  Therefore, every time a volunteer signs up for a shift, the following data needs to be recorded.  

![shift_rec_data](https://cloud.githubusercontent.com/assets/5384790/13832127/2d251064-eba7-11e5-9ae1-e5229324e7a0.png)

Similarly, once the icons that give dispatchers information about possible responders' desires and likeliness of response are implemented (#85), related data needs to be stored.  This will allow the Red Cross to know which features of the Incident Portal are valuable to dispatchers when they are staffing incidents.  The following columns needs to be added to the incidents_responder_assignments table. 

![icon_data](https://cloud.githubusercontent.com/assets/5384790/13832171/c19b92cc-eba7-11e5-9fa3-9575e6b62565.png)

**Comment by cecilia-donnelly** [comment]
As discussed yesterday, we don't necessarily need to store the newness/need/past.accept/past.declines information in a table (though we may), since those can always be recalculated on the fly.
