### ISSUE TITLE
Incidents | Notification Level | Show Recipients change "false" to "no"

### ISSUE THREAD

**Issue by jasonwinget** [redcross/arcdata#89]
In the recipients list the SMS column has false in it when the SMS is not being sent.  This is really geek speak and should be "no" or something more dispatcher friendly.

![false-geek](https://cloud.githubusercontent.com/assets/3647696/13902378/5f758058-ee13-11e5-9ed1-d12e7c0ddaf0.png)

**Comment by nchambe2** [comment]
@cecilia-donnelly Hey Cecilia, I was interested in working on this issue, but I'm unclear about where this particular view can be seen in the UI. Do you know how I can get to this particular page, and what type of user I need to be logged in as to view it?

**Comment by cecilia-donnelly** [comment]
@nchambe2 Hi Nicolette!  I'm psyched that you're interested in this one.  I'm not sure where it is, but it looks like it's related to the following files:
`app/views/incidents/notifications/_form.html.haml`
`app/views/incidents/notifications/recipients.html.haml` (<-- I think that's probably where you'd make the change)  
Possibly also:
`app/controllers/incidents/responder_messages_controller.rb`

I don't see where in the app this page shows up.  @jasonwinget, can you give us the path to this screenshot?

I expect you need to be logged in as someone with dispatch privileges, which for our sample data I think is the admin user.

**Comment by jasonwinget** [comment]
@nchambe2  and @cecilia-donnelly you will find this in the incident, the main page of the incident.  There is a **notification level**
 link on the main page.  After you choose a list in the first box (severity) then click on the **show recipients** link.  I am including another screen shot that includes the URL.

![notify](https://cloud.githubusercontent.com/assets/3647696/14413626/67eab878-ff45-11e5-99e6-5fad8b1bb8d7.png)

**Comment by cecilia-donnelly** [comment]
@jasonwinget thanks very much.  This actually shows a problem with our sample data, which I think I've rectified in commit f345fde.  That part of the details tab wasn't visible to us.  @nchambe2, if you pull down that commit you should see the "Notification Level" on the Details tab of any given incident, within the "Response" section and right above "Assistance."  I played around with the responders console a bit to try to get some recipients to show up in the "Show Recipients" section, but haven't had any success yet.  I'll keep looking at it.  Let me know if you get it to show up.

**Comment by jasonwinget** [comment]
That option is not likely configured for moat regions.  We just set it up
about 2 months ago here.

On Mon, Apr 11, 2016, 1:07 PM Cecilia Donnelly <notifications@github.com>
wrote:

> @jasonwinget <https://github.com/jasonwinget> thanks very much. This
> actually shows a problem with our sample data, which I think I've rectified
> in commit f345fde
> <https://github.com/redcross/arcdata/commit/f345fde59394a1123fbb52de1a6dc5f1f365cc5b>.
> That part of the details tab wasn't visible to us. @nchambe2
> <https://github.com/nchambe2>, if you pull down that commit you should
> see the "Notification Level" on the Details tab of any given incident,
> within the "Response" section and right above "Assistance." I played around
> with the responders console a bit to try to get some recipients to show up
> in the "Show Recipients" section, but haven't had any success yet. I'll
> keep looking at it. Let me know if you get it to show up.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/redcross/arcdata/issues/89#issuecomment-208481081>
>
-- 

--
Sent from Google's Inbox mobile

**Comment by cecilia-donnelly** [comment]
@jasonwinget oh, interesting.  You mean the notification link is not visible for many regions?  What do you use it for now that you have it?

By the way, @nchambe2, I think in order to have recipients show up in the "Show Recipients" area we'll need to add some entries to the "Severity" dropdown, and then associate people with those different severities.  I'm not quite sure how that works yet, but I'll keep looking into it.

**Comment by jasonwinget** [comment]
I am including some screen shots to tell the story @cecilia-donnelly to what we have configured.  We use to alert our casework team of follow up needed the next day, and we also use it to escalate it on large scale events to our larger team of disaster leadership.

![2016-04-12_19-41-01](https://cloud.githubusercontent.com/assets/3647696/14479663/99b92400-00e6-11e6-962b-1567bbfc020b.png)

![2016-04-12_19-39-37](https://cloud.githubusercontent.com/assets/3647696/14479665/a177327c-00e6-11e6-9dd3-2f9dd0bc5c29.png)


![2016-04-12_19-39-11](https://cloud.githubusercontent.com/assets/3647696/14479667/a6f30e2e-00e6-11e6-9e80-5fe52ec0a8ac.png)


![2016-04-12_19-38-34](https://cloud.githubusercontent.com/assets/3647696/14479673/a9f0717a-00e6-11e6-9f92-4b256f0becae.png)

**Comment by cecilia-donnelly** [comment]
@jasonwinget that is extremely helpful; thank you.

@nchambe2, it looks like we need to create at least one notification role and associate users with it in order to see the "SMS: false" interface in the first comment of this issue.  That's not so bad!  I'll look into doing that if you don't get to it first.
