### ISSUE TITLE
Seeds step fails in DCSOps setup

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/arcdata#91]
@lorenanicole reports that the `db:seeds` step fails to run when setting up a local instance of this project.  I'll try to reproduce and add more information here if/when I do.

**Comment by cecilia-donnelly** [comment]
@lorenanicole, I think I've successfully reproduced this!

I started the setup process fresh, by changing the database name in `database.yml` from `arcdata-dev` to `arcdata-dev2`.  When I ran `./bin/setup`, I got the following error:

```
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute: password
/home/cdonnelly/Documents/arcdata/db/seeds.rb:166:in `<top (required)>'
-e:1:in `<main>'
NoMethodError: undefined method `password=' for #<Roster::Person:0x00559a076ac498>
/home/cdonnelly/Documents/arcdata/db/seeds.rb:166:in `<top (required)>'
-e:1:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
```

More soon.

**Comment by lorenanicole** [comment]
@cecilia-donnelly I am so thrilled your sleuthing is paying off! I wish you much luck in `raking` it in (haaahaha see what I did there?!) !

**Comment by cecilia-donnelly** [comment]
Hmm, strange behavior.  It looks like I can make the script run without the `NoMethodError` by following these steps:

1. Create a new instance with a new db.
2. `git checkout dev-setup` and run `./bin/setup`, which fails.
3. `git checkout ec88f9307dbcbb6eec33d0307773df5372bb62f5` (this is right after the initial creation of the setup script) and run `./bin/setup`, which works.
4. `git checkout dev-setup` (i.e., back to the tip of the branch) and run `./bin/setup` again.  It now works.

After doing this, even dropping the database doesn't bring back the `NoMethodError`, which is very unexpected.

**Comment by lorenanicole** [comment]
Gross. Do you think best bet for now is to opt for these steps?

**Comment by cecilia-donnelly** [comment]
Oh, I was more leaving that comment as a note for myself.  I see it more as "what changed that made the error appear?" or "what the heck happens in the earlier version that makes it stop happening?"  If we can figure that out, then we can just make the change.  So, basically: I haven't given up yet!
